### ISSUE TITLE
Update @tanstack/react-query. Currently the library is using ^4.0.0 and this is causing issues with the QueryClientProvider not setting a queryClient.

### ISSUE THREAD

**Issue by mcornielje090404** [psteinroe/supabase-cache-helpers#192]
The QueryClientProvider on @tanstack/react-query does not work with this library in it's current version. Through testing I've found that it breaks at 4.3.0. 4.2.3 and below work fine. 

The issue that occurs is 'No QueryClient set, use QueryClientProvider to set one' seen below.

<img width="463" alt="Screenshot 2023-05-22 at 18 17 56" src="https://github.com/psteinroe/supabase-cache-helpers/assets/90604542/942813fa-73cf-4762-bc76-4e93db2c29e4">

I would like to have this looked at and a later version of tanstack react-query used in the library if possible.

**Comment by psteinroe** [comment]
Hey, thanks for reporting this issue. The [4.3.0 changelog](https://github.com/TanStack/query/releases/tag/v4.3.0) only lists esm support as relevant change. since this package lists tanstack query as peer dependency only, and exports both esm and cjs, I am afraid that it is very likely that the issue is related to you project setup. Could you provide a minimal reproduction?

**Comment by psteinroe** [comment]
I will setup a react-query example, and try to reproduce this there.

**Comment by psteinroe** [comment]
fixed in the latest release!

**Comment by mcornielje090404** [comment]
Awesome thank you
