### ISSUE TITLE
SWR useInfiniteScrollQuery return count

### ISSUE THREAD

**Issue by Than-DE** [psteinroe/supabase-cache-helpers#223]
**Is your feature request related to a problem? Please describe.**
I am using virtualization to improve the performance of infinite scrolling on a table and for that it would be useful to get the `count` of my supabase query. `useQuery` can return that but the infinite scroll query does not. Is there a specific reason for that?

**Describe the solution you'd like**
Like with `useQuery`, return the `count` if specified in the query:

```ts
const { data, loadMore, isValidating, count } = useInfiniteScrollQuery(
    supabase
      .from("table")
      .select("*", { count: "exact" })
    { pageSize: 10 }
  );
```

**Describe alternatives you've considered**
I could do a seperate counting query seperate from the cache helper to get the count, but it would be nicer if the helper could return that already.

**Additional context**
There might be a good reason to not return it here - would love to know more about that :)

**Comment by psteinroe** [comment]
hey @Than-DE, thanks for opening the issue.

When using count within a Supabase query, the returned number only counts the values for that particular query including all its filters. Since the infinite queries do page-wise queries with a `limit` and `offset` filter, the count returned by each of the queries would be either `limit` or a smaller value if it is the last page. To get the overall count, you will need to execute another query with the same filters. 

```tsx
// for this query
      const { data } = useInfiniteScrollQuery(
        client
          .from('contact')
          .select('id,username')
          .ilike('username', `something%`)
      );

// page-wise queries will be executed
client
          .from('contact')
          .select('id,username')
          .ilike('username', `something%`).range(0, 50)

// a count on this query would just return a value <= `50`. to get the full count, another query without the range filter is required.
```
