### ISSUE TITLE
Querying for embedded resources messes up the cache

### ISSUE THREAD

**Issue by dotellie** [psteinroe/supabase-cache-helpers#272]
**Describe the bug**

When performing a query with embedded resources (a query with a join in SQL speak), it seems the update mutation can't properly update the cache.

**To Reproduce**

1. Run a query:
```ts
useQuery(
  supabase
      .from("a_table")
      .select(
        "id,text,another_table(id,text)"
      )
);
```
2. Mutate an entity in the list:
```ts
const { trigger } = useUpdateMutation(
  supabase.from("a_table"),
  ["id"]
);
// ... later
trigger({ id: "the id", text: "new text" });
```

**Expected behavior**

In case of a list: the updates should apply to the list
- What actually happens: a duplicate item is added to the initial data from `useQuery`, containing the new data

In case of a `.single()`: the entity returned from the query should be updated
- What actually happens: `null` is returned from `useQuery`

**Additional context**

I would **really** like to be able to help out with this but unfortunately I have no idea how to really contribute. If some docs could be added to go over development environment setup, that would be amazing - then I would probably help out quite a bit in the future! ⭐

**Comment by psteinroe** [comment]
hey @dotellie, thanks for opening the issue.

I think this is the same root cause as similar issue I got aware of last week. unfortunately, the root cause is a design error and not a simple fix. For now, you should be able to temporary "fix" this by setting `revalidate` to true on the mutation. 

As you said, the codebase is quite hard to contribute to as of now. My plan is to first refactor it and make it more accessible for contributors, and then fix the bugs and minor feature requests. I hope to get all this done in the next 2-3 weeks.

**Comment by dotellie** [comment]
Thanks for the quick reply @psteinroe! I was actually looking around the code and was just starting to draw the same conclusion about it being non-trivial 😔 But hey, it sounds great if you're able to get it done so soon! If you'd like any help, just let me know. I have started improving the docs a little bit if that's interesting but I would also happily bounce ideas if you need to 😄

**Comment by psteinroe** [comment]
I appreciate any help! thanks for working on the docs. I hope that the code base will be much more accessible once the refactoring is done. some of the feature requests and bugs currently open should be fairly straightforward to implement then.

**Comment by psteinroe** [comment]
hey @dotellie! 

good news, I came up with a solution to this problem, and started with refactoring the codebase to make it more approachable (https://github.com/psteinroe/supabase-cache-helpers/pull/278).

I want to publish a new release early next week latest.

**Comment by dotellie** [comment]
Hey @psteinroe! That's awesome, good work! Really appreciate how quickly you were able to tackle this, especially considering it took a whole refactor to fix it ❤️ 

Not to be a downer though, but I still think this isn't entirely complete. It works for the most part, but my guess is that when some "advanced" foreign table filtering comes into the picture, this breaks down somewhat. Here's the piece of code that seems to produce same results as before:

```ts
  supabase
    .from("table1")
    .select(
      "id, created_at, name, table2 (id, created_at), view1 (id, created_at, table3 (id, name))"
    )
    .is("view1.table3.property", null)
    .order("created_at", {
      foreignTable: "view1",
      ascending: false,
    })
    .limit(1, { foreignTable: "view1.table3" })
    .order("created_at", {
      foreignTable: "table2",
      ascending: false,
    })
    .limit(1, { foreignTable: "table2" })
    .eq("id", id)
    .single();
```

Considering how quickly you figured the last issue out, I'm crossing my fingers this obfuscated code (taken from the codebase I'm working on) is enough for you to figure out what's going on, but feel free to ask for more info 😄

**Comment by psteinroe** [comment]
Hey @dotellie, thanks for the report. Can you provide a bit more details on what breaks? Maybe even a repro? I cannot think of a cause here, and I have queries of similar or larger complexity working just fine.

**Comment by dotellie** [comment]
Interesting... what I get is essentially that the app never stops "loading" the new state (even though it is committed correctly) and also the object mutated disappears from lists. I'll see if I can work on a repro tomorrow though I am slowly recovering from a sickness so definitely no promises 😅

**Comment by YaqoobM** [comment]
Hi @psteinroe, I'm encountering a similar issue which I think is related to this bug. I am manually updating the cache after performing the mutations server-side (which returns the select query generated from [buildNormalisedQuery](https://github.com/psteinroe/supabase-cache-helpers/blob/21b8f4c0c20422c18bd83275396b5dc3234ccaa8/packages/postgrest-core/src/fetch/build-normalized-query.ts) back to the client). This works fine until I use multiple joins in my query to the same table which then doesn't update the cache properly.

For example if I have the following query in my cache:
```js
supabase
  .from("table_1")
  .select(
    `id,
    image_1:images!image_1_id (src)
    image_2:images!image_2_id (src)
     `,
  )
  .eq("id", id)
  .single()
  .throwOnError();
```
I receive the following object from [normalizeResponse](https://github.com/psteinroe/supabase-cache-helpers/blob/21b8f4c0c20422c18bd83275396b5dc3234ccaa8/packages/postgrest-core/src/fetch/build-mutation-fetcher-response.ts) which updates the cache correctly.
```json
{ id: 1, images!image_1_id.src: "somewhere", images!image_2_id.src: "somewhere_else" }
```

The problem is when one of the image_id fields are set to ***NULL***, in this case normalizeResponse returns:
```json
{ id: 1, images: null, images!image_2_id.src: "somewhere_else" }
```
In this case the cache doesn't update correctly and both objects are set to null.
